version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guestbook
  tomcat:
    image: tomcat:jdk8
    entrypoint: /usr/local/tomcat/bin/catalina.sh jpda run
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - "./tomcat/webapps:/usr/local/tomcat/webapps"
      - "./tomcat/conf/context.xml:/usr/local/tomcat/conf/context.xml"
    environment:
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
volumes:
  mysql_data: